Fix CppCheck in MessageComposer.cpp
/retroshare-gui/src/gui/msgs/MessageComposer.cpp:750: warning:
Cppcheck(unusedVariable): Unused variable: gxsIds
/retroshare-gui/src/gui/msgs/MessageComposer.cpp:1015: warning:
Cppcheck(unusedVariable): Unused variable: groupIds
/retroshare-gui/src/gui/msgs/MessageComposer.cpp:1016: warning:
Cppcheck(unusedVariable): Unused variable: groupIt
/retroshare-gui/src/gui/msgs/MessageComposer.cpp:1488: error:
Cppcheck(iterators): Same iterator is used with different containers
'm_tagIds' and 'tagIds'.