Fix Warning in rscrypto.cpp
/libretroshare/src/crypto/rscrypto.cpp:149: error:
Cppcheck(syntaxError): Invalid number of character '(' when these macros
are defined: 'CRYPTO_DEBUG'.