Fix Warnings in GroupDefs.h
/trunk/retroshare-gui/src/gui/common/GroupDefs.h:26: warning: class
'RsGroupInfo' was previously declared as a struct [-Wmismatched-tags]
/trunk/retroshare-gui/src/gui/common/GroupDefs.h:31: error: unknown type
name 'QString'
/trunk/retroshare-gui/src/gui/common/GroupDefs.h:33: error: use of
undeclared identifier 'std'
/trunk/retroshare-gui/src/gui/common/GroupDefs.h:24: warning: macro name
is a reserved identifier
/trunk/retroshare-gui/src/gui/common/GroupDefs.h:31: warning: 'const'
type qualifier on return type has no effect