Fix CppCheck in p3idservice.cc
/libretroshare/src/services/p3idservice.cc:2017: warning:
Cppcheck(invalidScanfArgType_int): %d in format string (no. 1) requires
'int *' but the argument type is 'unsigned int *'.
/libretroshare/src/services/p3idservice.cc:2017: warning:
Cppcheck(invalidScanfArgType_int): %d in format string (no. 2) requires
'int *' but the argument type is 'unsigned int *'.
/libretroshare/src/services/p3idservice.cc:3921: error:
Cppcheck(uninitvar): Uninitialized variable: item
/libretroshare/src/services/p3idservice.cc:3985: warning:
Cppcheck(cstyleCast): C-style pointer casting